### ISSUE TITLE
links are dead

### ISSUE THREAD

**Issue by mangeurdenuage** [taktoa/guile-sly#3]
Hello friendly FSD maintainer here.
Today I was looking at your software in the fsd
https://directory.fsf.org/wiki/Sly
And the link for the home page is dead is there a new one ?
For now I have used the wayback machine to link to the website but maybe there is something more recent.
https://web.archive.org/web/20160404221653/https://dthompson.us/pages/software/sly.html
Could you please update ?

**Comment by taktoa** [comment]
Note that this isn't my project, I'm just mirroring it.
This is where I got it from: https://git.framasoft.org/a-guile-mind/sly/
EDIT: oops, I meant https://git.dthompson.us/sly.git

**Comment by mangeurdenuage** [comment]
Ho! sorry, thank you for informing me.
Have a good day and
Happy hacking
